ALTER TABLE person ADD COLUMN address VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE person ADD COLUMN zipcode INTEGER NULL DEFAULT NULL;
ALTER TABLE person ADD COLUMN city VARCHAR(50) NULL DEFAULT NULL;
